//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmClockWPFClient.AlarmSevice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/KMA.APZRP2019.AlarmClock.DBModels", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AlarmClockWPFClient.AlarmSevice.AlarmClock> _alarmClocksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid _guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _lastLoginTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AlarmClockWPFClient.AlarmSevice.AlarmClock> _alarmClocks {
            get {
                return this._alarmClocksField;
            }
            set {
                if ((object.ReferenceEquals(this._alarmClocksField, value) != true)) {
                    this._alarmClocksField = value;
                    this.RaisePropertyChanged("_alarmClocks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _email {
            get {
                return this._emailField;
            }
            set {
                if ((object.ReferenceEquals(this._emailField, value) != true)) {
                    this._emailField = value;
                    this.RaisePropertyChanged("_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _firstName {
            get {
                return this._firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this._firstNameField, value) != true)) {
                    this._firstNameField = value;
                    this.RaisePropertyChanged("_firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid _guid {
            get {
                return this._guidField;
            }
            set {
                if ((this._guidField.Equals(value) != true)) {
                    this._guidField = value;
                    this.RaisePropertyChanged("_guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _lastLoginTime {
            get {
                return this._lastLoginTimeField;
            }
            set {
                if ((this._lastLoginTimeField.Equals(value) != true)) {
                    this._lastLoginTimeField = value;
                    this.RaisePropertyChanged("_lastLoginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _lastName {
            get {
                return this._lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this._lastNameField, value) != true)) {
                    this._lastNameField = value;
                    this.RaisePropertyChanged("_lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _login {
            get {
                return this._loginField;
            }
            set {
                if ((object.ReferenceEquals(this._loginField, value) != true)) {
                    this._loginField = value;
                    this.RaisePropertyChanged("_login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _password {
            get {
                return this._passwordField;
            }
            set {
                if ((object.ReferenceEquals(this._passwordField, value) != true)) {
                    this._passwordField = value;
                    this.RaisePropertyChanged("_password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlarmClock", Namespace="http://schemas.datacontract.org/2004/07/KMA.APZRP2019.AlarmClock.DBModels", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class AlarmClock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid _guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _lastAlarmTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _nextAlarmTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlarmClockWPFClient.AlarmSevice.User _ownerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid _ownerGuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid _guid {
            get {
                return this._guidField;
            }
            set {
                if ((this._guidField.Equals(value) != true)) {
                    this._guidField = value;
                    this.RaisePropertyChanged("_guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _lastAlarmTime {
            get {
                return this._lastAlarmTimeField;
            }
            set {
                if ((this._lastAlarmTimeField.Equals(value) != true)) {
                    this._lastAlarmTimeField = value;
                    this.RaisePropertyChanged("_lastAlarmTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _nextAlarmTime {
            get {
                return this._nextAlarmTimeField;
            }
            set {
                if ((this._nextAlarmTimeField.Equals(value) != true)) {
                    this._nextAlarmTimeField = value;
                    this.RaisePropertyChanged("_nextAlarmTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlarmClockWPFClient.AlarmSevice.User _owner {
            get {
                return this._ownerField;
            }
            set {
                if ((object.ReferenceEquals(this._ownerField, value) != true)) {
                    this._ownerField = value;
                    this.RaisePropertyChanged("_owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid _ownerGuid {
            get {
                return this._ownerGuidField;
            }
            set {
                if ((this._ownerGuidField.Equals(value) != true)) {
                    this._ownerGuidField = value;
                    this.RaisePropertyChanged("_ownerGuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlarmSevice.IAlarmClockService")]
    public interface IAlarmClockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmClockService/GetAllUsers", ReplyAction="http://tempuri.org/IAlarmClockService/GetAllUsersResponse")]
        System.Collections.Generic.List<AlarmClockWPFClient.AlarmSevice.User> GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmClockService/GetAllUsers", ReplyAction="http://tempuri.org/IAlarmClockService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AlarmClockWPFClient.AlarmSevice.User>> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmClockService/AddUser", ReplyAction="http://tempuri.org/IAlarmClockService/AddUserResponse")]
        void AddUser(AlarmClockWPFClient.AlarmSevice.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmClockService/AddUser", ReplyAction="http://tempuri.org/IAlarmClockService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(AlarmClockWPFClient.AlarmSevice.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmClockServiceChannel : AlarmClockWPFClient.AlarmSevice.IAlarmClockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlarmClockServiceClient : System.ServiceModel.ClientBase<AlarmClockWPFClient.AlarmSevice.IAlarmClockService>, AlarmClockWPFClient.AlarmSevice.IAlarmClockService {
        
        public AlarmClockServiceClient() {
        }
        
        public AlarmClockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlarmClockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmClockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmClockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<AlarmClockWPFClient.AlarmSevice.User> GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AlarmClockWPFClient.AlarmSevice.User>> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public void AddUser(AlarmClockWPFClient.AlarmSevice.User user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(AlarmClockWPFClient.AlarmSevice.User user) {
            return base.Channel.AddUserAsync(user);
        }
    }
}
