//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmClockWPFClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAlarmClockService")]
    public interface IAlarmClockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmClockService/GetAllUsers", ReplyAction="http://tempuri.org/IAlarmClockService/GetAllUsersResponse")]
        System.Collections.Generic.List<KMA.APZRP2019.AlarmClock.DBModels.User> GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmClockService/GetAllUsers", ReplyAction="http://tempuri.org/IAlarmClockService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<KMA.APZRP2019.AlarmClock.DBModels.User>> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmClockService/AddUser", ReplyAction="http://tempuri.org/IAlarmClockService/AddUserResponse")]
        void AddUser(KMA.APZRP2019.AlarmClock.DBModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmClockService/AddUser", ReplyAction="http://tempuri.org/IAlarmClockService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(KMA.APZRP2019.AlarmClock.DBModels.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmClockServiceChannel : AlarmClockWPFClient.ServiceReference1.IAlarmClockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlarmClockServiceClient : System.ServiceModel.ClientBase<AlarmClockWPFClient.ServiceReference1.IAlarmClockService>, AlarmClockWPFClient.ServiceReference1.IAlarmClockService {
        
        public AlarmClockServiceClient() {
        }
        
        public AlarmClockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlarmClockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmClockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmClockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KMA.APZRP2019.AlarmClock.DBModels.User> GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<KMA.APZRP2019.AlarmClock.DBModels.User>> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public void AddUser(KMA.APZRP2019.AlarmClock.DBModels.User user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(KMA.APZRP2019.AlarmClock.DBModels.User user) {
            return base.Channel.AddUserAsync(user);
        }
    }
}
