// <auto-generated />
namespace KMA.APZRP2019.AlarmClock.EntityFrameworkWrapper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserMigrationV4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserMigrationV4));
        
        string IMigrationMetadata.Id
        {
            get { return "201911232031418_UserMigrationV4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
